services:
  mysql:
    image: mysql:5.7
    container_name: mysql-message-service
    environment:
      MYSQL_DATABASE: messages
      MYSQL_ROOT_PASSWORD: passsword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysqlconfig/init.sql:/docker-entrypoint-initdb.d/1.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10